### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by sstanislavska** [sstanislavska/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ITStan** [comment]
I am one of the best in Street Fighters.
I am a wandering warrior, a serious person with a hard temper and sometimes a bad sense of humor.
My main goal is to master my fighting style perfectly. I do not compete with others, the only competition that challenges me is myself.

**Comment by sstanislavska** [comment]
Спасибо большое!
